{{- /*
Copyright 2023 Dynatrace LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/}}

apiVersion: v1
kind: Service
metadata:
  name: {{ include "unguard.fullname" . }}-{{.Values.redis.name}}
  labels:
    app.kubernetes.io/name: {{.Values.redis.name}}
    app.kubernetes.io/part-of: {{ include "unguard.fullname" . }}
spec:
  type: {{.Values.redis.service.type}}
  selector:
    app.kubernetes.io/name: {{.Values.redis.name}}
    app.kubernetes.io/part-of: {{ include "unguard.fullname" . }}
  ports:
  {{- .Values.redis.service.ports | toYaml | nindent 4 }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "unguard.fullname" . }}-{{.Values.redis.name}}-{{.Values.redis.configMap.metadata.name}}
data:
  redis-config: |
    maxmemory 256mb
    maxmemory-policy allkeys-lru
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "unguard.fullname" . }}-{{.Values.redis.name}}
  labels:
    app.kubernetes.io/name: {{.Values.redis.name}}
    app.kubernetes.io/part-of: {{ include "unguard.fullname" . }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{.Values.redis.name}}
      app.kubernetes.io/part-of: {{ include "unguard.fullname" . }}
  strategy:
    type: {{.Values.redis.deployment.strategy.type}}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{.Values.redis.name}}
        app.kubernetes.io/part-of: {{ include "unguard.fullname" . }}
    spec:
      containers:
        - name: {{.Values.redis.name}}
          image: {{.Values.redis.deployment.container.image.repository}}:{{.Values.redis.deployment.container.image.tag}}
          imagePullPolicy: {{.Values.redis.deployment.container.image.pullPolicy}}
          command:
            - redis-server
            - "/config/redis.conf"
          env:
            - name: MASTER
              value: "true"
          ports:
            - containerPort: {{.Values.redis.deployment.container.ports.containerPort}}
          readinessProbe:
            periodSeconds: 5
            tcpSocket:
              port: 6379
          livenessProbe:
            periodSeconds: 5
            tcpSocket:
              port: 6379
          volumeMounts:
            - mountPath: /data
              name: redis-data
            - mountPath: /config
              name: config
          resources:
            limits:
              memory: 512Mi
              cpu: 125m
            requests:
              cpu: 70m
              memory: 200Mi
      volumes:
        - name: redis-data
          emptyDir: { }
        - name: config
          configMap:
            name: {{ include "unguard.fullname" . }}-{{.Values.redis.name}}-{{.Values.redis.configMap.metadata.name}}
            items:
              - key: redis-config
                path: redis.conf
