# Default values for unguard-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
kubernetesClusterDomain: cluster.local

localDev:
  minikube:
    enabled: true
  kind:
    enabled: false


aws:
  enabled: false


profileService:
  name: profile-service

  service:
    type: ClusterIP
    ports:
      - targetPort: 8080
        port: 80
  deployment:
    strategy:
      type: Recreate
    container:
      image:
        repository: ghcr.io/dynatrace-oss/unguard/unguard-profile-service
        tag: 21d9943b5f45e4c615296ad48a8f4b969972ab70
        pullPolicy: IfNotPresent
      ports:
        containerPort: 8080
      env:
        otelMetricsExporter: none
        otelResourceAttributes: service.name=unguard-profile-service
        otelTracesExporter: none
        springDatasourcePassword: password
        springDatasourceUrl: jdbc:h2:file:./database/bio
        springDatasourceUsername: sa
      livenessProbe:
        httpGet:
          path: /healthz
          port: 8080
        initialDelaySeconds: 5
        periodSeconds: 15

userSimulator:
  name: user-simulator

  cronJob:
    schedule: "*/3 * * * *"
    startingDeadlineSeconds: 180
    jobTemplate:
      restartPolicy: OnFailure

      container:
        image:
          repository: ghcr.io/dynatrace-oss/unguard/unguard-user-simulator
          tag: 21d9943b5f45e4c615296ad48a8f4b969972ab70
          pullPolicy: IfNotPresent

        env:
          FRONTEND_ADDR: unguard-envoy-proxy:8080/ui
          SIMULATE_PRIVATE_RANGES: false

        resources:
          requests:
            cpu: 10m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi


membershipService:
  name: membership-service

  service:
    type: ClusterIP
    ports:
      - targetPort: 8080
        port: 80

  deployment:
    strategy:
      type: Recreate
    container:
      image:
        repository: ghcr.io/dynatrace-oss/unguard/unguard-profile-service
        tag: 21d9943b5f45e4c615296ad48a8f4b969972ab70
        pullPolicy: IfNotPresent
      ports:
        containerPort: 8083
      env:
        ASPNETCORE_ENVIRONMENT: Development
        SERVER_PORT: 8083
        API_PATH: /membership-service
        MARIADB_SERVICE: unguard-mariadb
        MARIADB_PASSWORD:
          secretKeyRef:
            name: unguard-mariadb
            key: mariadb-root-password


userAuthService:
  name: user-auth-service

  service:
    type: ClusterIP
    ports:
      - targetPort: 9091
        port: 80

  deployment:
    strategy:
      type: Recreate
    container:
      image:
        repository: ghcr.io/dynatrace-oss/unguard/unguard-ad-service
        tag: 21d9943b5f45e4c615296ad48a8f4b969972ab70
        pullPolicy: IfNotPresent
      ports:
        containerPort: 9091
      env:
        SERVER_PORT: 9091
        MARIADB_SERVICE: unguard-mariadb
        MARIADB_PASSWORD:
          secretKeyRef:
            name: unguard-mariadb
            key: mariadb-root-password
        JAEGER_SERVICE_NAME: unguard-user-auth-service
        JAEGER_AGENT_HOST: jaeger-agent # change depending on your jaeger deployment
        JAEGER_SAMPLER_TYPE: const
        JAEGER_SAMPLER_PARAM: 0
        JAEGER_DISABLED: true
        ASPNETCORE_ENVIRONMENT: Production
        API_PATH: /ad-service
        USER_AUTH_SERVICE_ADDRESS: unguard-user-auth-service


adService:
  name: ad-service

  service:
    type: ClusterIP
    ports:
      - targetPort: 8082
        port: 80

  deployment:
    strategy:
      type: Recreate
    container:
      image:
        repository: ghcr.io/dynatrace-oss/unguard/unguard-ad-service
        tag: 21d9943b5f45e4c615296ad48a8f4b969972ab70
        pullPolicy: IfNotPresent
      ports:
        containerPort: 8082
      env:
        JAEGER_SERVICE_NAME: unguard-ad-service
        JAEGER_AGENT_HOST: jaeger-agent # change depending on your jaeger deployment
        JAEGER_SAMPLER_TYPE: const
        JAEGER_SAMPLER_PARAM: 0
        JAEGER_DISABLED: true
        ASPNETCORE_ENVIRONMENT: Production
        SERVER_PORT: 8082
        API_PATH: /ad-service
        USER_AUTH_SERVICE_ADDRESS: unguard-user-auth-service


envoyProxy:
  name: envoy-proxy

  service:
    type: ClusterIP
    ports:
      - name: http
        targetPort: 8080
        port: 8080
      - name: health
        targetPort: 8081
        port: 8081

  deployment:
    strategy:
      type: RollingUpdate
    container:
      image:
        repository: ghcr.io/dynatrace-oss/unguard/unguard-envoy-proxy
        tag: 21d9943b5f45e4c615296ad48a8f4b969972ab70
        pullPolicy: IfNotPresent
      ports:
        - name: http
          containerPort: 8080
        - name: health
          containerPort: 8081


microblogService:
  name: microblog-service

  service:
    type: ClusterIP
    ports:
      - targetPort: 8080
        port: 80

  deployment:
    strategy:
      type: Recreate
    container:
      image:
        repository: ghcr.io/dynatrace-oss/unguard/unguard-microblog-service
        tag: 21d9943b5f45e4c615296ad48a8f4b969972ab70
        pullPolicy: IfNotPresent
      ports:
        containerPort: 8080
      env:
        SERVER_PORT: 8080
        JAEGER_SERVICE_NAME: unguard-microblog-service
        JAEGER_AGENT_HOST: jaeger-agent # change depending on your jaeger deployment
        JAEGER_SAMPLER_TYPE: const
        JAEGER_SAMPLER_PARAM: 0
        OPENTRACING_JAEGER_ENABLED: false
        REDIS_SERVICE_ADDRESS: unguard-redis
        USER_AUTH_SERVICE_ADDRESS: unguard-user-auth-service


dbReadinessCheck:
  name: db-readiness-check
  image:
    repository: ghcr.io/dynatrace-oss/unguard/unguard-db-readiness-check
    tag: latest
    pullPolicy: IfNotPresent
  command: /check.sh
  env:
    MYSQL_USER: root
    MYSQL_HOST: unguard-mariadb
    MYSQL_PASSWORD:
      secretKeyRef:
        name: unguard-mariadb
        key: mariadb-root-password

statusService:
  name: status-service

  service:
    type: ClusterIP
    ports:
      - targetPort: 8083
        port: 80

  serviceAccount:
    name: unguard-status

  role:
    name: status-role
    rules:
      - apiGroups: [ "apps" ]
        resources: [ "deployments" ]
        verbs: [ "get", "list" ]
      - apiGroups: [ "" ]
        resources: [ "pods" ]
        verbs: [ "get", "list" ]

  roleBindings:
    name: status-rolebinding
    subjects:
      - kind: ServiceAccount
        name: unguard-status
        apiGroup: ""
    roleRef:
      kind: Role
      name: status-role
      apiGroup: rbac.authorization.k8s.io

  deployment:
    strategy:
      type: Recreate
    container:
      image:
        repository: ghcr.io/dynatrace-oss/unguard/unguard-status-service
        tag: 21d9943b5f45e4c615296ad48a8f4b969972ab70
        pullPolicy: IfNotPresent
      ports:
        containerPort: 8083
      env:
        SERVER_PORT: 8083
        API_PATH: /status-service
        KUBERNETES_NAMESPACE: unguard
        IGNORED_DEPLOYMENTS: unguard-user-simulator # add deployments to ignore separated by spaces

################################################################
proxyService:
  name: proxy-service

  service:
    type: ClusterIP
    ports:
      - targetPort: 8081
        port: 80

  serviceAccount:
    name: unguard-proxy

  role:
    name: proxy-role
    rules:
      - apiGroups: [""] # "" indicates the core API group
        resources: ["pods"]
        verbs: ["create", "list", "get"]
      - apiGroups: [""]
        resources: ["pods/exec"]
        verbs: ["create"]

  roleBindings:
    name: proxy-rolebinding
    subjects:
      - kind: ServiceAccount
        name: unguard-proxy
        apiGroup: ""
    roleRef:
      kind: Role
      name: proxy-role
      apiGroup: rbac.authorization.k8s.io

  deployment:
    strategy:
      type: Recreate
    container:
      image:
        repository: ghcr.io/dynatrace-oss/unguard/proxy-status-service
        tag: 21d9943b5f45e4c615296ad48a8f4b969972ab70
        pullPolicy: IfNotPresent
      ports:
        containerPort: 8081
      env:
        SERVER_PORT: 8081
        JAEGER_SERVICE_NAME: unguard-proxy-service
        JAEGER_AGENT_HOST: jaeger-agent # change depending on your jaeger deployment
        JAEGER_SAMPLER_TYPE: const
        JAEGER_SAMPLER_PARAM: 0
        OPENTRACING_JAEGER_ENABLED: false


frontend:
  name: frontend

  service:
    type: ClusterIP
    ports:
      - targetPort: 3000
        port: 80

  deployment:
    strategy:
      type: Recreate
    container:
      image:
        repository: ghcr.io/dynatrace-oss/unguard/unguard-frontend
        tag: 21d9943b5f45e4c615296ad48a8f4b969972ab70
        pullPolicy: IfNotPresent
      ports:
        containerPort: 3000
      env:
        JAEGER_SERVICE_NAME: unguard-frontend
        JAEGER_AGENT_HOST: jaeger-agent # change depending on your jaeger deployment
        JAEGER_SAMPLER_TYPE: const
        JAEGER_SAMPLER_PARAM: 0
        JAEGER_DISABLED: true
        MICROBLOG_SERVICE_ADDRESS: unguard-microblog-service
        PROXY_SERVICE_ADDRESS: unguard-proxy-service
        USER_AUTH_SERVICE_ADDRESS: unguard-user-auth-service
        AD_SERVICE_ADDRESS: unguard-ad-service
        STATUS_SERVICE_ADDRESS: unguard-status-service
        MEMBERSHIP_SERVICE_ADDRESS: unguard-membership-service
        PROFILE_SERVICE_ADDRESS: unguard-profile-service
        FRONTEND_BASE_PATH: /ui
        AD_SERVICE_BASE_PATH: /ad-service
        MEMBERSHIP_SERVICE_BASE_PATH: /membership-service
        STATUS_SERVICE_BASE_PATH: /status-service



mariadb:
  primary:
    persistence:
      enabled: false
