# Default values for unguard-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
localDev:
  minikube:
    enabled: true
  kind:
    enabled: false


aws:
  enabled: false

services:
  adService:
    image:
      repository: ghcr.io/dynatrace-oss/unguard/ad-service
      tag: v1.2.0
      pullPolicy: IfNotPresent
  envoyProxy:
    image:
      repository: ghcr.io/dynatrace-oss/unguard/envoy-proxy
      tag: v1.2.0
      pullPolicy: IfNotPresent
  dbReadinessCheck:
    image:
      repository: ghcr.io/dynatrace-oss/unguard/db-readiness-check
      tag: v1.2.0
      pullPolicy: IfNotPresent
  frontend:
    image:
      repository: ghcr.io/dynatrace-oss/unguard/frontend
      tag: v1.2.0
      pullPolicy: IfNotPresent
  microblogService:
    image:
      repository: ghcr.io/dynatrace-oss/unguard/microblog-service
      tag: v1.2.0
      pullPolicy: IfNotPresent
  proxyService:
    image:
      repository: ghcr.io/dynatrace-oss/unguard/proxy-service
      tag: v1.2.0
      pullPolicy: IfNotPresent
  userSimulator:
    image:
      repository: ghcr.io/dynatrace-oss/unguard/user-simulator
      tag: v1.2.0
      pullPolicy: IfNotPresent


mariadb:
  primary:
    persistence:
      enabled: false
