# Default values for unguard-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
lovaldev:
  minikube:
    enabled: true
  kind:
    enabled: false


aws:
  enabled: false


mariadb:
  primary:
    persistence:
      enabled: false
