[tool.poetry]
name = "payment-service"
version = "0.1.0"
description = ""
authors = ["Fabian Oraze <fabian.oraze@dynatrace.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.8.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
