{{- /*
Copyright 2023 Dynatrace LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/}}

apiVersion: v1
kind: Service
metadata:
  name: unguard-membership-service
  labels:
    app.kubernetes.io/name: membership-service
    app.kubernetes.io/part-of: unguard
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: membership-service
    app.kubernetes.io/part-of: unguard
  ports:
    - targetPort: 8083
      port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: unguard-membership-service
  labels:
    app.kubernetes.io/name: membership-service
    app.kubernetes.io/part-of: unguard
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: membership-service
      app.kubernetes.io/part-of: unguard
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: membership-service
        app.kubernetes.io/part-of: unguard
    spec:
      containers:
        - name: membership-service
          image: unguard-membership-service
          ports:
            - containerPort: 8083
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
            - name: SERVER_PORT
              value: "8083"
            - name: API_PATH
              value: "/membership-service"
            - name: MARIADB_SERVICE
              value: "unguard-mariadb"
            - name: MARIADB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: unguard-mariadb
                  key: mariadb-root-password
      initContainers:
        - name: db-readiness-check
          image: {{.Values.services.dbReadinessCheck.image.repository}}:{{.Values.services.dbReadinessCheck.image.tag}}
          command: ["/check.sh"]
          env:
            - name: MYSQL_USER
              value: "root"
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: unguard-mariadb
                  key: mariadb-root-password
            - name: MYSQL_HOST
              value: "unguard-mariadb"


