---
name: Dependabot High/Critical -> Assign to Copilot (Scheduled)

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch: {}

# Note: This 'permissions' block only affects the default GITHUB_TOKEN, not your App token.
# It's fine to keep minimal; your App token governs its own permissions.
permissions:
  contents: read
  issues: write
  security-events: read

concurrency:
  group: dependabot-triage
  cancel-in-progress: true

jobs:
  triage-high-critical:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub App installation token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.AI_APP_ID }}
          private-key: ${{ secrets.AI_APP_PRIVATE_KEY }}
          # Ensure the app is installed on this repository
          owner: AppSec-AI-Initiative-Dev
          repositories: |
            unguard

      - name: Cache last run timestamp
        uses: actions/cache@v3
        with:
          path: last-run.txt
          key: dependabot-triage-lastrun-${{ github.run_id }}
          restore-keys: |
            dependabot-triage-lastrun-

      - name: Fetch new Dependabot alerts and create consolidated issue
        uses: actions/github-script@v7
        with:
          github-token: ${{ steps['app-token'].outputs.token }}
          script: |
            const fs = require('fs');
            const path = require('path');
            const owner = context.repo.owner;
            const repo = context.repo.repo;

            // Get last run timestamp
            let lastRunTime = new Date(0); // Default to epoch if no previous run
            const lastRunFile = 'last-run.txt';
            if (fs.existsSync(lastRunFile)) {
              try {
                const lastRunStr = fs.readFileSync(lastRunFile, 'utf8').trim();
                lastRunTime = new Date(lastRunStr);
                core.info(`Last run was at: ${lastRunTime.toISOString()}`);
              } catch (e) {
                core.warning(`Failed to read last run time: ${e.message}`);
              }
            } else {
              core.info('No previous run timestamp found, treating all alerts as new');
            }

            // Current run timestamp
            const currentRunTime = new Date();

            async function listAlerts() {
              try {
                const perPage = 100;
                let page = 1;
                let all = [];
                for (;;) {
                  const res = await github.request("GET /repos/{owner}/{repo}/dependabot/alerts", {
                    owner,
                    repo,
                    state: "open",
                    severity: "high,critical",
                    per_page: perPage,
                    page
                  });
                  all = all.concat(res.data);
                  if (res.data.length < perPage) break;
                  page++;
                }
                return all;
              } catch (e) {
                core.error(`Failed to list Dependabot alerts: ${e.status || ""} ${e.message}`);
                if (e.response?.headers) core.info(`Response headers: ${JSON.stringify(e.response.headers)}`);
                if (e.response?.data) core.info(`Response body: ${JSON.stringify(e.response.data)}`);
                throw e;
              }
            }

            async function consolidatedIssueExists(runMarker) {
              try {
                const q = `repo:${owner}/${repo} is:issue in:body "${runMarker}"`;
                const res = await github.rest.search.issuesAndPullRequests({ q });
                return res.data.total_count > 0;
              } catch (e) {
                core.warning(`Search API failed, proceeding without dedupe: ${e.status || ""} ${e.message}`);
                return false;
              }
            }

            const allAlerts = await listAlerts();
            if (!allAlerts.length) {
              core.info("No open High/Critical Dependabot alerts found.");
              // Still update timestamp for next run
              fs.writeFileSync(lastRunFile, currentRunTime.toISOString());
              return;
            }

            // Filter alerts that are new since last run
            const newAlerts = allAlerts.filter(alert => {
              const createdAt = new Date(alert.created_at);
              return createdAt > lastRunTime;
            });

            if (!newAlerts.length) {
              core.info(`Found ${allAlerts.length} total alerts, but no new alerts since ${lastRunTime.toISOString()}`);
              // Update timestamp for next run
              fs.writeFileSync(lastRunFile, currentRunTime.toISOString());
              return;
            }

            core.info(`Found ${newAlerts.length} new alert(s) out of ${allAlerts.length} total alerts`);

            // Create run marker for this batch
            const runMarker = `dependabot-alerts-batch: ${currentRunTime.toISOString()}`;

            // Check if we already created an issue for this batch
            if (await consolidatedIssueExists(runMarker)) {
              core.info(`Consolidated issue already exists for this run, skipping.`);
              return;
            }

            // Build consolidated issue
            const alertDetails = newAlerts.map(alert => {
              const advisory = alert.security_advisory || {};
              const vuln = alert.security_vulnerability || {};
              const dependency = alert.dependency || {};

              const ghsa =
                advisory.ghsa_id ||
                (advisory.identifiers || []).find(i => i.type === "GHSA")?.value ||
                "N/A";
              const cves = (advisory.identifiers || [])
                .filter(i => i.type === "CVE")
                .map(i => i.value);

              const severity = (advisory.severity || "unknown").toLowerCase();

              const pkg =
                vuln.package?.name ||
                dependency.package?.name ||
                "dependency";
              const ecosystem =
                vuln.package?.ecosystem ||
                dependency.package?.ecosystem ||
                "N/A";

              const affected = vuln.vulnerable_version_range || "N/A";
              const fixedIn = vuln.first_patched_version?.identifier || "N/A";
              const manifest = dependency.manifest_path || "N/A";
              const alertId = alert.number || alert.id;

              const alertUrl =
                alert.html_url ||
                (alertId
                  ? `https://github.com/${owner}/${repo}/security/dependabot/${alertId}`
                  : "N/A");

              return {
                alertId,
                severity,
                ghsa,
                cves,
                pkg,
                ecosystem,
                affected,
                fixedIn,
                manifest,
                alertUrl
              };
            });

            // Sort by severity (critical first, then high)
            alertDetails.sort((a, b) => {
              if (a.severity === 'critical' && b.severity !== 'critical') return -1;
              if (b.severity === 'critical' && a.severity !== 'critical') return 1;
              return a.pkg.localeCompare(b.pkg);
            });

            const criticalCount = alertDetails.filter(a => a.severity === 'critical').length;
            const highCount = alertDetails.filter(a => a.severity === 'high').length;

            const title = `Dependabot Security Alerts: ${criticalCount} Critical, ${highCount} High`;

            const alertSections = alertDetails.map(alert => [
              `### ${alert.severity.toUpperCase()}: ${alert.ghsa} in ${alert.pkg}`,
              `- **Alert URL**: ${alert.alertUrl}`,
              `- **Package**: ${alert.pkg} (${alert.ecosystem})`,
              `- **Affected versions**: ${alert.affected}`,
              `- **Fixed in**: ${alert.fixedIn}`,
              `- **GHSA**: ${alert.ghsa}`,
              `- **CVEs**: ${alert.cves.length ? alert.cves.join(", ") : "N/A"}`,
              `- **Manifest path**: ${alert.manifest}`,
              ""
            ].join("\n"));

            const body = [
              `This issue was created automatically for ${newAlerts.length} new High/Critical Dependabot alert(s) detected on ${currentRunTime.toISOString()}.`,
              "",
              `**Summary**: ${criticalCount} Critical, ${highCount} High severity alerts`,
              "",
              "## Alert Details",
              "",
              ...alertSections,
              "---",
              "",
              `**Tracking**: ${runMarker}`,
              `**Alert IDs**: ${alertDetails.map(a => a.alertId).join(", ")}`
            ].join("\n");

            // Determine overall severity for labeling
            const overallSeverity = criticalCount > 0 ? "critical" : "high";

            // Names of labels we're adding
            const labelsToAdd = ["security", "dependabot", overallSeverity, "verification:pending"];

            try {
              // Primary: suggestedActors (CAN_BE_ASSIGNED), per guidance
              const repoInfo = await github.graphql(
                `query($owner: String!, $repo: String!) {
                  repository(owner: $owner, name: $repo) {
                    id
                    suggestedActors(capabilities: [CAN_BE_ASSIGNED], first: 100) {
                      nodes {
                        login
                        __typename
                        ... on Bot { id }
                        ... on User { id }
                      }
                    }
                  }
                }`,
                { owner, repo }
              );

              const repositoryId = repoInfo.repository.id;

              // Debug: suggestedActors
              const actors = (repoInfo &&
                              repoInfo.repository &&
                              repoInfo.repository.suggestedActors &&
                              Array.isArray(repoInfo.repository.suggestedActors.nodes))
                                ? repoInfo.repository.suggestedActors.nodes
                                : [];
              try {
                core.info("Debug: suggestedActors (CAN_BE_ASSIGNED) count: " + actors.length);
                const preview = actors.slice(0, 25);
                core.info("Debug: suggestedActors preview (first " + preview.length + "): " + JSON.stringify(preview, null, 2));
              } catch (dbgErr) {
                core.warning("Debug: Failed to stringify suggestedActors: " + (dbgErr && dbgErr.message ? dbgErr.message : String(dbgErr)));
              }

              // Try to pick copilot-swe-agent from suggestedActors
              let copilotId = null;
              const fromSuggested = actors.find(function(n) {
                return n && n.login === "copilot-swe-agent" && n.id;
              });
              if (fromSuggested && fromSuggested.id) {
                copilotId = fromSuggested.id;
                core.info("Debug: Found copilot-swe-agent in suggestedActors.");
              }

              // Fallback 1: assignableUsers with exact login
              if (!copilotId) {
                try {
                  const assignableRes = await github.graphql(
                    `query($owner: String!, $repo: String!, $login: String!) {
                      repository(owner: $owner, name: $repo) {
                        assignableUsers(query: $login, first: 10) {
                          nodes { id login __typename }
                        }
                      }
                    }`,
                    { owner, repo, login: "copilot-swe-agent" }
                  );
                  const nodes = (assignableRes &&
                                 assignableRes.repository &&
                                 assignableRes.repository.assignableUsers &&
                                 Array.isArray(assignableRes.repository.assignableUsers.nodes))
                                   ? assignableRes.repository.assignableUsers.nodes
                                   : [];
                  core.info("Debug: assignableUsers('copilot-swe-agent') count: " + nodes.length);
                  const exact = nodes.find(function(n) { return n && n.login === "copilot-swe-agent" && n.id; });
                  if (exact) {
                    copilotId = exact.id;
                    core.info("Debug: Found copilot-swe-agent via assignableUsers.");
                  }
                } catch (assignErr) {
                  core.warning("Debug: assignableUsers lookup failed: " + (assignErr && assignErr.message ? assignErr.message : String(assignErr)));
                }
              }

              // Fallback 2: REST list assignees, use node_id
              if (!copilotId) {
                try {
                  let page = 1;
                  let found = null;
                  for (;;) {
                    const res = await github.rest.issues.listAssignees({
                      owner,
                      repo,
                      per_page: 100,
                      page
                    });
                    const arr = Array.isArray(res.data) ? res.data : [];
                    const hit = arr.find(function(u) { return u && u.login === "copilot-swe-agent" && (u.node_id || u.id); });
                    if (hit) {
                      // node_id is the GraphQL node ID
                      copilotId = hit.node_id || null;
                      if (!copilotId) {
                        core.warning("Debug: copilot-swe-agent found via REST but missing node_id; cannot assign with assigneeIds.");
                      } else {
                        core.info("Debug: Found copilot-swe-agent via REST listAssignees.");
                      }
                      found = hit;
                      break;
                    }
                    if (arr.length < 100) break;
                    page++;
                  }
                  if (!found) {
                    core.info("Debug: copilot-swe-agent not found via REST listAssignees.");
                  }
                } catch (restErr) {
                  core.warning("Debug: REST listAssignees failed: " + (restErr && restErr.message ? restErr.message : String(restErr)));
                }
              }

              if (!copilotId) {
                throw new Error("COPILOT_NOT_ASSIGNABLE");
              }

              // Create the issue using GraphQL with assigneeIds (Copilot)
              const createIssueRes = await github.graphql(
                `mutation($repositoryId: ID!, $title: String!, $body: String!, $assigneeIds: [ID!]) {
                  createIssue(input: {
                    repositoryId: $repositoryId,
                    title: $title,
                    body: $body,
                    assigneeIds: $assigneeIds
                  }) {
                    issue {
                      number
                      url
                    }
                  }
                }`,
                {
                  repositoryId,
                  title,
                  body,
                  assigneeIds: [copilotId]
                }
              );

              const issueNumber = createIssueRes.createIssue.issue.number;

              // Add labels via REST (simpler)
              await github.rest.issues.addLabels({
                owner,
                repo,
                issue_number: issueNumber,
                labels: labelsToAdd
              });

              core.info(`Created consolidated issue #${issueNumber} and assigned to copilot-swe-agent via assigneeIds`);

            } catch (e) {
              // Fallback path: create without Copilot assignment, add a label and comment
              if (e.message === "COPILOT_NOT_ASSIGNABLE" || e.status === 422) {
                const created = await github.rest.issues.create({
                  owner,
                  repo,
                  title,
                  body,
                  labels: [...labelsToAdd, "copilot-assignment-failed"]
                });
                await github.rest.issues.createComment({
                  owner,
                  repo,
                  issue_number: created.data.number,
                  body: "Automatic assignment to the Copilot coding agent (copilot-swe-agent) could not be completed via GraphQL (assigneeIds). Please ensure Copilot coding agent is enabled for this repository and that this GitHub App token can list assignees."
                });
                core.warning(`Copilot assignment unavailable; created issue #${created.data.number} with fallback label.`);
              } else if (e.status === 403) {
                core.error(`Issues API denied (403). Verify the GitHub App has 'Issues: Read and write' and is installed on this repository. Message: ${e.message}`);
                throw e;
              } else {
                core.error(`Issue creation/assignment error: ${e.status || ""} ${e.message}`);
                throw e;
              }
            }

            // Save current timestamp for next run
            fs.writeFileSync(lastRunFile, currentRunTime.toISOString());
            core.info(`Updated last run timestamp to: ${currentRunTime.toISOString()}`)
