
name: Build and Push Docker Images to ECR

permissions:
  id-token: write
  contents: read

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
  # No need to set AWS_REGION and ECR_REPOSITORY as env variables for OIDC; use secrets directly in steps
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ECR_ROLE_ARN }}
          role-session-name: GitHubActions

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push Docker images
        env:
          ECR_REPOSITORY: ${{ secrets.AWS_ECR_REPOSITORY }}
        run: |
          IMAGE_TAG=latest
          for dockerfile in $(find ./src -name Dockerfile); do
            SERVICE=$(basename $(dirname $dockerfile))
            IMAGE_URI="${ECR_REPOSITORY}:${SERVICE}-${IMAGE_TAG}"
            docker build -t $IMAGE_URI -f $dockerfile $(dirname $dockerfile)
            docker push $IMAGE_URI
          done
