name: Publish images
on:
  push:
    branches:
      - feature/transition-unguard-to-helm

jobs:
  build:
    name: Publish on container registry
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3



      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ vars.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}



      - name: Publish Helm chart to GHCR
        run: |
          helm package chart
          helm push unguard-0.8.0.tgz oci://${{ vars.REGISTRY }}/${{ github.repository }}/chart
