name: Publish images
on:
  push:
    branches:
      - main
      - 'release/**'
jobs:
  build:
    name: Publish on container registry
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Get release version
        if: startsWith(github.ref_name, 'release')
        uses: actions-ecosystem/action-regex-match@v2
        id: release-version
        with:
          text: ${{ github.ref_name }}
          regex: '^release\/(.*)$'

      - name: Set image tag
        run: |
          echo "IMAGE_TAG=${{ github.sha }}" >> $GITHUB_ENV

      - name: Set image release tag
        if: ${{ steps.release-version.outputs.match != '' }}
        run: |
          echo "IMAGE_TAG=${{ steps.release-version.outputs.group1 }}" >> $GITHUB_ENV

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ vars.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache layers
        uses: actions/cache@v3
        with:
          path: "${{ github.workspace }}/.skaffold/cache"
          key: skaffold-${{ hashFiles('**/cache') }}
          restore-keys: |
            skaffold-

      - name: Run Skaffold build pipeline
        uses: hiberbee/github-action-skaffold@1.26.0
        id: build
        with:
          command: build
          skip-tests: true
          tag: ${{ env.IMAGE_TAG }}
          repository: ${{ vars.REGISTRY }}/${{ github.repository }}
          push: true
